version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5433"
    networks:
      - app_network

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_PORT: 5433
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      POSTGRESQL_URI: ${POSTGRESQL_URI}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    networks:
      - app_network

networks:
  app_network: